version: '3'

services:
  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: docker_db
      # Optional: Give a name to the database, otherwise
      # use the default value POSTGRES_USER as a database name (user in this case.)

    ports:
      - "5433:5432"
    volumes:
      - ./docker/db:/var/lib/postgresql/data

  phppgadmin:
    container_name: ${PROJECT_NAME}-phppgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 1111
